# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-24
    - ANDROID_ABI=armeabi-v7a


notifications:
      webhooks:
        urls:
          - https://webhooks.gitter.im/e/9f05d841054e90296f28
        on_success: never
        on_failure: always
        on_start: never

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository
    - extra-android-support
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

script:
    - ./gradlew build jacocoTestReport assembleAndroidTest
    - ./gradlew clean assembleDebug test lint

before_install:
  - pip install --user codecov

after_success:
  - codecov

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle